version: "3"

x-basic-setting: &basic-setting
  init: true
  restart: unless-stopped
  logging:
    driver: json-file
    options:
      max-size: "2G"
      max-file: "2"
      compress: "true"

services:
  autoheal:
    <<: *basic-setting
    image: docker.io/willfarrell/autoheal:latest
    container_name: autoheal
    network_mode: "none"
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
      - AUTOHEAL_START_PERIOD=60
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
